name: Deploy to Cloudflare Workers (Production)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - name: 🌳 Setup Node.js 23 & pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: 🧹 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🌟 Build OpenNextJS Cloudflare
        run: pnpm run build:cf

      - name: 🚀 Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
